development:
  adapter: postgresql
  encoding: unicode
  database: buzurg_development
  pool: 5
  username: hara
  password:


test:
  adapter: postgresql
  encoding: unicode
  database: buzurg_test
  pool: 5
  username: hara
  password:
